FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml ./
RUN mvn -q -DskipTests dependency:go-offline

COPY src ./src
COPY database ./database
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre AS runtime
WORKDIR /app

COPY --from=build /app/target/auction-app-1.0-SNAPSHOT.jar ./app.jar
COPY --from=build /app/database ./database

EXPOSE 10000
ENTRYPOINT ["java", "-jar", "app.jar"]
