package com.nhom1.auction.common.protocol;

public enum MessageType {
    LOGIN,
    REGISTER,

    LIST_AUCTIONS,
    GET_AUCTION_DETAIL,
    PLACE_BID,
    LIST_MY_BIDS,

    CREATE_AUCTION,
    LIST_MY_LISTINGS,

    AUTO_BID_CONFIG,
    ADMIN_LIST_USERS,
    ADMIN_DELETE_USER,
    ADMIN_LIST_AUCTIONS,
    ADMIN_CANCEL_AUCTION,
    PROCESS_PAYMENT,

    PUSH_BID_UPDATE,
    PUSH_AUCTION_ENDED
}
